#  
# Copyright (C) 2016-2019 phantombot.tv
#  
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#  
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

version: '3'
services:
  phantombot:
    container_name: phantombot-nightly
    image: gmt2001/phantombot-nightly:latest
    ports:
      - "25000:25000"
    restart: always
    volumes:
      - /opt/PhantomBot/addons
      - /opt/PhantomBot/config
      - /opt/PhantomBot/dbbackup
      - /opt/PhantomBot/logs
      - /opt/PhantomBot/scripts/custom
      - /opt/PhantomBot/scripts/discord/custom
      - /opt/PhantomBot/scripts/lang/custom
    environment:
      # ------ Override any botlogin.txt variable here, with the PHANTOMBOT_ prefix
      # Twitch bot user (Required)
      - PHANTOMBOT_USER=
      # Twitch bot user OAuth token (https://twitchapps.com/tmi/) (Required)
      - PHANTOMBOT_OAUTH=
      # Twitch caster channel OAuth token (https://phantombot.tv/oauth/)
      # - PHANTOMBOT_APIOAUTH=
      # Twitch caster channel (Required)
      - PHANTOMBOT_CHANNEL=
      # Webinterface username
      #- PHANTOMBOT_PANELUSER=
      # Webinterface password
      #- PHANTOMBOT_PANELPASSWORD=